### PR TITLE
Allow underscores in param names

### PR DESCRIPTION
**Pull request by OskarDamkjaer**
We should support underscores in names. It seems åäö should also be supported from this [documentation](https://neo4j.com/docs/cypher-manual/current/syntax/naming/).

I am guess this would need a new release as well?

### CODE REVIEW

**Comment by OskarDamkjaer** [comment]
@huboneo Could you have a look at this?

**Comment by OskarDamkjaer** [comment]
Hmm come to think of it we should probably allow _ as the first char of a name as well

**Comment by OskarDamkjaer** [comment]
@huboneo  I've not go merge rights, could you merge? And also walk me through how i get these changes to the browser?

**Comment by huboneo** [comment]
@OskarDamkjaer It should be enough to bump the dependency once I publish

**Comment by huboneo** [comment]
@OskarDamkjaer `@neo4j/browser-lambda-parser@1.0.5` is published!

**Pull request merged**
